name: Dependent Issues
description: Mark issues as dependent on another
author: Ahmed T. Ali

inputs:
  label:
    required: false
    description: The label to use to mark dependent issues
    default: dependent

  check_issues:
    required: false
    description: Enable checking for dependencies in issues
    default: off

  keywords:
    required: false
    description: A comma-separated list of keywords
    default: depends on, blocked by

runs:
  using: node12
  main: ./index.js
